services:
  db:
    image: postgres:13
    container_name: odoo-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  web:
    image: odoo:18.0
    container_name: odoo-web
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./odoo:/mnt/odoo
      - ./custom_addons:/mnt/custom_addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf

volumes:
  odoo-db-data:
  